name: modeller

services:
  - name: modeller
    type: web
    description: "Backend eines Modellierungsassistenten"
    instance:
      plan: eco
    ports:
      - name: http
        port: 5000
    routes:
      - name: main
        path: /
    build:
      type: buildpack
    env:
      - key: FLASK_ENV
        value: production
    run:
      command: "python backend.py"
